#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


# Compositor
picom -f &

# wallpaper
nitrogen --restore &

# Bluetooth
blueman-applet	&

# Status Bar

dte(){
	dte="$(date +"%I:%M %A, %b %d %Y ")"
	echo -e "$dte"
}

upd(){
	upd="$(checkupdates | wc -l)"
	echo -e " $upd updates"

}

bat(){
	bat="$(cat /sys/class/power_supply/axp288_fuel_gauge/capacity)"
	echo -e "$bat%"

}

while true; do
	xsetroot -name "$(dte) | $(upd) | $(bat)"
	sleep 1m
done &

# Mount Pendrives
udiskie &

#dunst
dunst &

# Execute DWM
exec dwm
